apiVersion: tekton.dev/v1beta1
kind: Pipeline

metadata:
  name: nodejs-pipeline
  namespace: bjex
spec:
  params:
  - name: IMAGE
    description: Image description
    type: string
    default: "docker.io/judi2021/mynode-app"
  - name: TAG
    description: Preferred tag
    default: latest
  workspaces:
  - name: linked-workspace
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: linked-workspace
    params:
    - name: url
      value: https://github.com/cynogen127/tekton
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
  - name: build-push-image
    taskRef:
      name: buildah
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: linked-workspace
    params:
    - name: IMAGE
      value: "$(params.IMAGE):$(params.TAG)"
    - name: CONTEXT
      value: "src"
    - name: FORMAT
      value: "docker"
  - name: create-deployment
    taskRef:
      name: kubernetes-actions
    runAfter:
    - build-push-image
    params:
    - name: script
      value: |
        kubectl apply --filename https://github.com/cynogen127/deployment-test/blob/main/deploy.yaml
    workspaces:
    - name: manifest-dir
      workspace: linked-workspace
