
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/cynogen127/node-s.git
